title: Sebastian Just
description: CV from Sebastian Just
url: https://sebastian-just.de/
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
